// Mock data for development and demonstration purposes
// Remove this file when going live with actual data

export const mockInstructors = [
  {
    id: "mock-inst-1",
    name: "Sarah M.",
    email: "sarah.m@example.com",
    location: "Bondi, NSW",
    certifications: ["Reformer", "Cadillac", "Mat"],
    experience_years: 8,
    hourly_rate: 85,
    bio: "Passionate Pilates instructor with comprehensive certifications and specializations in performance enhancement and injury prevention.",
    avatar_url: "/woman-instructor.png",
    rating: 4.9,
    total_classes: 450,
    availability_count: 12,
  },
  {
    id: "mock-inst-2",
    name: "James C.",
    email: "james.c@example.com",
    location: "Surry Hills, NSW",
    certifications: ["Reformer", "Mat", "Chair"],
    experience_years: 5,
    hourly_rate: 75,
    bio: "Former athlete turned Pilates instructor, focusing on performance enhancement and injury prevention.",
    avatar_url: "/man-instructor.png",
    rating: 5.0,
    total_classes: 320,
    availability_count: 8,
  },
  {
    id: "mock-inst-3",
    name: "Emma R.",
    email: "emma.r@example.com",
    location: "Manly, NSW",
    certifications: ["Reformer", "Cadillac", "Mat", "Tower"],
    experience_years: 12,
    hourly_rate: 95,
    bio: "Classical Pilates specialist trained in New York. Expert in pre/postnatal and injury recovery programs.",
    avatar_url: "/woman-pilates.jpg",
    rating: 5.0,
    total_classes: 680,
    availability_count: 15,
  },
  {
    id: "mock-inst-4",
    name: "Michael T.",
    email: "michael.t@example.com",
    location: "Newtown, NSW",
    certifications: ["Mat", "Reformer"],
    experience_years: 3,
    hourly_rate: 65,
    bio: "Contemporary Pilates instructor with a focus on mindful movement and breath work for all fitness levels.",
    avatar_url: "/fit-man-gym.png",
    rating: 4.7,
    total_classes: 180,
    availability_count: 10,
  },
  {
    id: "mock-inst-5",
    name: "Lisa K.",
    email: "lisa.k@example.com",
    location: "Paddington, NSW",
    certifications: ["Reformer", "Mat", "Barrel"],
    experience_years: 6,
    hourly_rate: 80,
    bio: "Rehabilitation specialist with physiotherapy background. Experienced in working with chronic pain and post-surgery recovery.",
    avatar_url: "/woman-instructor.png",
    rating: 4.9,
    total_classes: 390,
    availability_count: 14,
  },
  {
    id: "mock-inst-6",
    name: "David L.",
    email: "david.l@example.com",
    location: "Bondi Junction, NSW",
    certifications: ["Reformer", "Cadillac", "Chair"],
    experience_years: 7,
    hourly_rate: 88,
    bio: "Comprehensive instructor specializing in athletic conditioning and sports-specific Pilates training programs.",
    avatar_url: "/fit-man-gym.png",
    rating: 5.0,
    total_classes: 425,
    availability_count: 11,
  },
]

export const mockStudios = [
  {
    id: "mock-studio-1",
    name: "Core Pilates Studio",
    email: "info@corepilates.com.au",
    location: "Bondi Beach, NSW",
    description: "Premium boutique studio with 8 reformers and full equipment suite",
    avatar_url: "/bright-pilates-studio.png",
    active_jobs: 3,
    total_hires: 45,
  },
  {
    id: "mock-studio-2",
    name: "Flow Movement",
    email: "hello@flowmovement.com.au",
    location: "Surry Hills, NSW",
    description: "Contemporary Pilates studio focusing on athletic performance",
    avatar_url: "/modern-studio.jpg",
    active_jobs: 2,
    total_hires: 28,
  },
]

export const mockCoverRequests = [
  {
    id: "mock-cover-1",
    studio_id: "mock-studio-1",
    studio_name: "Core Pilates Studio",
    title: "Urgent: Reformer Class Cover Needed",
    date: "2025-10-28",
    time: "09:00 AM",
    duration: "55 minutes",
    class_type: "Reformer Level 2",
    rate: "$85/class",
    status: "urgent",
    description: "Need experienced reformer instructor for morning class. Regular instructor called in sick.",
    required_equipment: ["Reformer"],
    location: "Bondi Beach, NSW",
    created_at: "2025-10-26T08:00:00Z",
  },
  {
    id: "mock-cover-2",
    studio_id: "mock-studio-2",
    studio_name: "Flow Movement",
    title: "Weekend Mat Class Cover",
    date: "2025-10-29",
    time: "10:30 AM",
    duration: "45 minutes",
    class_type: "Mat Pilates All Levels",
    rate: "$70/class",
    status: "open",
    description: "Looking for mat instructor for Saturday morning class.",
    required_equipment: ["Mat"],
    location: "Surry Hills, NSW",
    created_at: "2025-10-25T14:00:00Z",
  },
  {
    id: "mock-cover-3",
    studio_id: "mock-studio-1",
    studio_name: "Core Pilates Studio",
    title: "Cadillac Private Session",
    date: "2025-10-30",
    time: "02:00 PM",
    duration: "60 minutes",
    class_type: "Private Cadillac",
    rate: "$120/session",
    status: "open",
    description: "Private client needs Cadillac session. Client has shoulder injury history.",
    required_equipment: ["Cadillac"],
    location: "Bondi Beach, NSW",
    created_at: "2025-10-24T10:00:00Z",
  },
]

export const mockAvailability = [
  {
    id: "mock-avail-1",
    instructor_id: "mock-inst-1",
    instructor_name: "Sarah M.",
    date: "2025-10-28",
    start_time: "08:00 AM",
    end_time: "12:00 PM",
    type: "Cover Available",
    location: "Bondi, NSW",
    equipment: ["Reformer", "Cadillac", "Mat"],
    rate: "$85/hour",
  },
  {
    id: "mock-avail-2",
    instructor_id: "mock-inst-2",
    instructor_name: "James C.",
    date: "2025-10-29",
    start_time: "09:00 AM",
    end_time: "01:00 PM",
    type: "Cover Available",
    location: "Surry Hills, NSW",
    equipment: ["Reformer", "Mat"],
    rate: "$75/hour",
  },
  {
    id: "mock-avail-3",
    instructor_id: "mock-inst-3",
    instructor_name: "Emma R.",
    date: "2025-10-28",
    start_time: "02:00 PM",
    end_time: "06:00 PM",
    type: "Cover Available",
    location: "Manly, NSW",
    equipment: ["Reformer", "Cadillac", "Mat", "Tower"],
    rate: "$95/hour",
  },
]

export const mockJobs = [
  {
    id: "mock-job-1",
    studio_id: "mock-studio-1",
    studio_name: "Core Pilates Studio",
    title: "Senior Reformer Instructor",
    type: "Part-time",
    location: "Bondi Beach, NSW",
    rate: "$80-95/hour",
    description:
      "Seeking experienced reformer instructor for 15-20 hours per week. Must have comprehensive certification and 5+ years experience.",
    requirements: ["Reformer certification", "5+ years experience", "Insurance", "First Aid"],
    posted_date: "2025-10-20",
    status: "open",
    applications: 8,
  },
  {
    id: "mock-job-2",
    studio_id: "mock-studio-2",
    studio_name: "Flow Movement",
    title: "Mat Pilates Instructor",
    type: "Casual",
    location: "Surry Hills, NSW",
    rate: "$65-75/class",
    description: "Looking for mat instructor for weekend classes. Great for building your client base.",
    requirements: ["Mat certification", "2+ years experience", "Insurance"],
    posted_date: "2025-10-22",
    status: "open",
    applications: 5,
  },
]

export const mockReferrals = [
  {
    id: "mock-ref-1",
    referrer_name: "Sarah M.",
    referred_name: "Jessica B.",
    referred_type: "Instructor",
    status: "completed",
    reward: "$50",
    date: "2025-09-15",
  },
  {
    id: "mock-ref-2",
    referrer_name: "Sarah M.",
    referred_name: "Zen Pilates Studio",
    referred_type: "Studio",
    status: "pending",
    reward: "$100",
    date: "2025-10-10",
  },
]

export const mockEarnings = {
  thisMonth: 2450,
  lastMonth: 2180,
  pending: 340,
  total: 18750,
  breakdown: [
    { month: "Oct", amount: 2450 },
    { month: "Sep", amount: 2180 },
    { month: "Aug", amount: 2340 },
    { month: "Jul", amount: 1980 },
    { month: "Jun", amount: 2100 },
    { month: "May", amount: 2200 },
  ],
}

export const mockApplications = [
  {
    id: "mock-app-1",
    job_title: "Senior Reformer Instructor",
    studio_name: "Core Pilates Studio",
    applied_date: "2025-10-21",
    status: "under_review",
    type: "permanent",
  },
  {
    id: "mock-app-2",
    job_title: "Weekend Mat Class Cover",
    studio_name: "Flow Movement",
    applied_date: "2025-10-25",
    status: "accepted",
    type: "cover",
  },
  {
    id: "mock-app-3",
    job_title: "Private Cadillac Session",
    studio_name: "Core Pilates Studio",
    applied_date: "2025-10-24",
    status: "pending",
    type: "cover",
  },
]

export const mockMessages = [
  {
    id: "mock-msg-1",
    from: "Core Pilates Studio",
    preview: "Thanks for applying! We'd love to schedule an interview...",
    time: "2 hours ago",
    unread: true,
  },
  {
    id: "mock-msg-2",
    from: "Flow Movement",
    preview: "Confirmed for Saturday 10:30 AM class. See you then!",
    time: "1 day ago",
    unread: false,
  },
]

export const mockPlatformStats = {
  totalUsers: 342,
  activeJobs: 28,
  completedCovers: 1247,
  monthlyRevenue: 8450,
  newUsersThisMonth: 23,
  activeInstructors: 250,
  activeStudios: 92,
  pendingVerifications: 5,
}
